---
nginx:
  sites:
    test.cluster.local:
      document_root: /opt/server/test
      ssl_enabled: true
    ci.cluster.local:
      document_root: /opt/server/ci
      ssl_enabled: true
    status.cluster.local:
      document_root: /opt/server/status
      ssl_enabled: true
  ssl:
    certificate_path: /etc/ssl/certs
    private_key_path: /etc/ssl/private
security:
  fail2ban:
    enabled: true
  ufw:
    enabled: true
  ssh:
    disable_root: true
    password_auth: false
