---
galaxy_info:
  role_name: nginx_multisite
  author: Chef Example
  description: Configures nginx with multiple SSL-enabled subdomains
  company: Example
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: EL
      versions:
        - all
  galaxy_tags:
    - nginx
    - web
    - ssl
    - security
  standalone: true
dependencies: []
