---
- name: Include security tasks
  ansible.builtin.import_tasks: security.yml
- name: Include nginx tasks
  ansible.builtin.import_tasks: nginx.yml
- name: Include ssl tasks
  ansible.builtin.import_tasks: ssl_new.yml
- name: Include sites tasks
  ansible.builtin.import_tasks: sites.yml
